### ISSUE TITLE
腾讯审核失败，说需要在注册的界面显示用户的昵称

### ISSUE THREAD

**Issue by myquant** [fantasticfears/qq_connect#4]

**Comment by myquant** [comment]
![a](https://cloud.githubusercontent.com/assets/7598526/8949529/66fdcb26-35e7-11e5-9c03-c726f679090a.jpg)

说界面必须显示用户的昵称，否则认证不通过，能否加上用户的昵称

**Comment by fantasticfears** [comment]
显示到全名区域是否可以？

**Comment by myquant** [comment]
感谢回复。刚才和他们几轮沟通，现在终于通过了。挑刺主要两点：一是验证回来后还要输入邮箱，说是诱导用户输入QQ邮箱；二是说没有显示用户的昵称。我后来截图，重定向回来的完善资料界面是有用户昵称的。

 

发件人: Erick Guan [mailto:notifications@github.com] 
发送时间: 2015年7月29日 14:55
收件人: fantasticfears/qq_connect
抄送: myquant
主题: Re: [qq_connect] 腾讯审核失败，说需要在注册的界面显示用户的昵称 (#4)

 

显示到全名区域是否可以？

**Comment by fantasticfears** [comment]
恭喜。

腾讯根本就没有给出获取邮箱地址的 API 接口。如果他们提供了，就可以直接创建账号，根本不需要再次填写信息。
